/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-19 16:59:56 UTC)
 * on 2013-06-19 at 17:40:34 UTC 
 * Modify at your own risk.
 */

package com.prescriptionwriter.prescriptionendpoint;

/**
 * Service definition for Prescriptionendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PrescriptionendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Prescriptionendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://nfcprescriptionwriter.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "prescriptionendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Prescriptionendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Prescriptionendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPrescription".
   *
   * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
   * any optional parameters, call the {@link GetPrescription#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPrescription getPrescription(java.lang.String id) throws java.io.IOException {
    GetPrescription result = new GetPrescription(id);
    initialize(result);
    return result;
  }

  public class GetPrescription extends PrescriptionendpointRequest<com.prescriptionwriter.prescriptionendpoint.model.Prescription> {

    private static final String REST_PATH = "prescription/{id}";

    /**
     * Create a request for the method "getPrescription".
     *
     * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
     * any optional parameters, call the {@link GetPrescription#execute()} method to invoke the remote
     * operation. <p> {@link GetPrescription#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPrescription(java.lang.String id) {
      super(Prescriptionendpoint.this, "GET", REST_PATH, null, com.prescriptionwriter.prescriptionendpoint.model.Prescription.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPrescription setAlt(java.lang.String alt) {
      return (GetPrescription) super.setAlt(alt);
    }

    @Override
    public GetPrescription setFields(java.lang.String fields) {
      return (GetPrescription) super.setFields(fields);
    }

    @Override
    public GetPrescription setKey(java.lang.String key) {
      return (GetPrescription) super.setKey(key);
    }

    @Override
    public GetPrescription setOauthToken(java.lang.String oauthToken) {
      return (GetPrescription) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPrescription setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPrescription) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPrescription setQuotaUser(java.lang.String quotaUser) {
      return (GetPrescription) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPrescription setUserIp(java.lang.String userIp) {
      return (GetPrescription) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetPrescription setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPrescription set(String parameterName, Object value) {
      return (GetPrescription) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPrescription".
   *
   * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
   * any optional parameters, call the {@link InsertPrescription#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.prescriptionwriter.prescriptionendpoint.model.Prescription}
   * @return the request
   */
  public InsertPrescription insertPrescription(com.prescriptionwriter.prescriptionendpoint.model.Prescription content) throws java.io.IOException {
    InsertPrescription result = new InsertPrescription(content);
    initialize(result);
    return result;
  }

  public class InsertPrescription extends PrescriptionendpointRequest<com.prescriptionwriter.prescriptionendpoint.model.Prescription> {

    private static final String REST_PATH = "prescription";

    /**
     * Create a request for the method "insertPrescription".
     *
     * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
     * any optional parameters, call the {@link InsertPrescription#execute()} method to invoke the
     * remote operation. <p> {@link InsertPrescription#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.prescriptionwriter.prescriptionendpoint.model.Prescription}
     * @since 1.13
     */
    protected InsertPrescription(com.prescriptionwriter.prescriptionendpoint.model.Prescription content) {
      super(Prescriptionendpoint.this, "POST", REST_PATH, content, com.prescriptionwriter.prescriptionendpoint.model.Prescription.class);
    }

    @Override
    public InsertPrescription setAlt(java.lang.String alt) {
      return (InsertPrescription) super.setAlt(alt);
    }

    @Override
    public InsertPrescription setFields(java.lang.String fields) {
      return (InsertPrescription) super.setFields(fields);
    }

    @Override
    public InsertPrescription setKey(java.lang.String key) {
      return (InsertPrescription) super.setKey(key);
    }

    @Override
    public InsertPrescription setOauthToken(java.lang.String oauthToken) {
      return (InsertPrescription) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPrescription setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPrescription) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPrescription setQuotaUser(java.lang.String quotaUser) {
      return (InsertPrescription) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPrescription setUserIp(java.lang.String userIp) {
      return (InsertPrescription) super.setUserIp(userIp);
    }

    @Override
    public InsertPrescription set(String parameterName, Object value) {
      return (InsertPrescription) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPrescription".
   *
   * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
   * any optional parameters, call the {@link ListPrescription#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPrescription listPrescription() throws java.io.IOException {
    ListPrescription result = new ListPrescription();
    initialize(result);
    return result;
  }

  public class ListPrescription extends PrescriptionendpointRequest<com.prescriptionwriter.prescriptionendpoint.model.CollectionResponsePrescription> {

    private static final String REST_PATH = "prescription";

    /**
     * Create a request for the method "listPrescription".
     *
     * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
     * any optional parameters, call the {@link ListPrescription#execute()} method to invoke the
     * remote operation. <p> {@link ListPrescription#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPrescription() {
      super(Prescriptionendpoint.this, "GET", REST_PATH, null, com.prescriptionwriter.prescriptionendpoint.model.CollectionResponsePrescription.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPrescription setAlt(java.lang.String alt) {
      return (ListPrescription) super.setAlt(alt);
    }

    @Override
    public ListPrescription setFields(java.lang.String fields) {
      return (ListPrescription) super.setFields(fields);
    }

    @Override
    public ListPrescription setKey(java.lang.String key) {
      return (ListPrescription) super.setKey(key);
    }

    @Override
    public ListPrescription setOauthToken(java.lang.String oauthToken) {
      return (ListPrescription) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPrescription setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPrescription) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPrescription setQuotaUser(java.lang.String quotaUser) {
      return (ListPrescription) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPrescription setUserIp(java.lang.String userIp) {
      return (ListPrescription) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPrescription setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPrescription setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPrescription set(String parameterName, Object value) {
      return (ListPrescription) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePrescription".
   *
   * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
   * any optional parameters, call the {@link RemovePrescription#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemovePrescription removePrescription(java.lang.String id) throws java.io.IOException {
    RemovePrescription result = new RemovePrescription(id);
    initialize(result);
    return result;
  }

  public class RemovePrescription extends PrescriptionendpointRequest<com.prescriptionwriter.prescriptionendpoint.model.Prescription> {

    private static final String REST_PATH = "prescription/{id}";

    /**
     * Create a request for the method "removePrescription".
     *
     * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
     * any optional parameters, call the {@link RemovePrescription#execute()} method to invoke the
     * remote operation. <p> {@link RemovePrescription#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePrescription(java.lang.String id) {
      super(Prescriptionendpoint.this, "DELETE", REST_PATH, null, com.prescriptionwriter.prescriptionendpoint.model.Prescription.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePrescription setAlt(java.lang.String alt) {
      return (RemovePrescription) super.setAlt(alt);
    }

    @Override
    public RemovePrescription setFields(java.lang.String fields) {
      return (RemovePrescription) super.setFields(fields);
    }

    @Override
    public RemovePrescription setKey(java.lang.String key) {
      return (RemovePrescription) super.setKey(key);
    }

    @Override
    public RemovePrescription setOauthToken(java.lang.String oauthToken) {
      return (RemovePrescription) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePrescription setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePrescription) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePrescription setQuotaUser(java.lang.String quotaUser) {
      return (RemovePrescription) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePrescription setUserIp(java.lang.String userIp) {
      return (RemovePrescription) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovePrescription setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePrescription set(String parameterName, Object value) {
      return (RemovePrescription) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePrescription".
   *
   * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
   * any optional parameters, call the {@link UpdatePrescription#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.prescriptionwriter.prescriptionendpoint.model.Prescription}
   * @return the request
   */
  public UpdatePrescription updatePrescription(com.prescriptionwriter.prescriptionendpoint.model.Prescription content) throws java.io.IOException {
    UpdatePrescription result = new UpdatePrescription(content);
    initialize(result);
    return result;
  }

  public class UpdatePrescription extends PrescriptionendpointRequest<com.prescriptionwriter.prescriptionendpoint.model.Prescription> {

    private static final String REST_PATH = "prescription";

    /**
     * Create a request for the method "updatePrescription".
     *
     * This request holds the parameters needed by the the prescriptionendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePrescription#execute()} method to invoke the
     * remote operation. <p> {@link UpdatePrescription#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.prescriptionwriter.prescriptionendpoint.model.Prescription}
     * @since 1.13
     */
    protected UpdatePrescription(com.prescriptionwriter.prescriptionendpoint.model.Prescription content) {
      super(Prescriptionendpoint.this, "PUT", REST_PATH, content, com.prescriptionwriter.prescriptionendpoint.model.Prescription.class);
    }

    @Override
    public UpdatePrescription setAlt(java.lang.String alt) {
      return (UpdatePrescription) super.setAlt(alt);
    }

    @Override
    public UpdatePrescription setFields(java.lang.String fields) {
      return (UpdatePrescription) super.setFields(fields);
    }

    @Override
    public UpdatePrescription setKey(java.lang.String key) {
      return (UpdatePrescription) super.setKey(key);
    }

    @Override
    public UpdatePrescription setOauthToken(java.lang.String oauthToken) {
      return (UpdatePrescription) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePrescription setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePrescription) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePrescription setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePrescription) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePrescription setUserIp(java.lang.String userIp) {
      return (UpdatePrescription) super.setUserIp(userIp);
    }

    @Override
    public UpdatePrescription set(String parameterName, Object value) {
      return (UpdatePrescription) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Prescriptionendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Prescriptionendpoint}. */
    @Override
    public Prescriptionendpoint build() {
      return new Prescriptionendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PrescriptionendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPrescriptionendpointRequestInitializer(
        PrescriptionendpointRequestInitializer prescriptionendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(prescriptionendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
