/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-05 16:09:48 UTC)
 * on 2013-06-15 at 20:01:04 UTC 
 * Modify at your own risk.
 */

package com.prescriptiontracker.patientendpoint;

/**
 * Service definition for Patientendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PatientendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Patientendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://PrescriptionWriter.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "patientendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Patientendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Patientendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPatient".
   *
   * This request holds the parameters needed by the the patientendpoint server.  After setting any
   * optional parameters, call the {@link GetPatient#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPatient getPatient(java.lang.String id) throws java.io.IOException {
    GetPatient result = new GetPatient(id);
    initialize(result);
    return result;
  }

  public class GetPatient extends PatientendpointRequest<com.prescriptiontracker.patientendpoint.model.Patient> {

    private static final String REST_PATH = "patient/{id}";

    /**
     * Create a request for the method "getPatient".
     *
     * This request holds the parameters needed by the the patientendpoint server.  After setting any
     * optional parameters, call the {@link GetPatient#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPatient#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPatient(java.lang.String id) {
      super(Patientendpoint.this, "GET", REST_PATH, null, com.prescriptiontracker.patientendpoint.model.Patient.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPatient setAlt(java.lang.String alt) {
      return (GetPatient) super.setAlt(alt);
    }

    @Override
    public GetPatient setFields(java.lang.String fields) {
      return (GetPatient) super.setFields(fields);
    }

    @Override
    public GetPatient setKey(java.lang.String key) {
      return (GetPatient) super.setKey(key);
    }

    @Override
    public GetPatient setOauthToken(java.lang.String oauthToken) {
      return (GetPatient) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPatient setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPatient) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPatient setQuotaUser(java.lang.String quotaUser) {
      return (GetPatient) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPatient setUserIp(java.lang.String userIp) {
      return (GetPatient) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetPatient setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPatient set(String parameterName, Object value) {
      return (GetPatient) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPatient".
   *
   * This request holds the parameters needed by the the patientendpoint server.  After setting any
   * optional parameters, call the {@link InsertPatient#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.prescriptiontracker.patientendpoint.model.Patient}
   * @return the request
   */
  public InsertPatient insertPatient(com.prescriptiontracker.patientendpoint.model.Patient content) throws java.io.IOException {
    InsertPatient result = new InsertPatient(content);
    initialize(result);
    return result;
  }

  public class InsertPatient extends PatientendpointRequest<com.prescriptiontracker.patientendpoint.model.Patient> {

    private static final String REST_PATH = "patient";

    /**
     * Create a request for the method "insertPatient".
     *
     * This request holds the parameters needed by the the patientendpoint server.  After setting any
     * optional parameters, call the {@link InsertPatient#execute()} method to invoke the remote
     * operation. <p> {@link InsertPatient#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.prescriptiontracker.patientendpoint.model.Patient}
     * @since 1.13
     */
    protected InsertPatient(com.prescriptiontracker.patientendpoint.model.Patient content) {
      super(Patientendpoint.this, "POST", REST_PATH, content, com.prescriptiontracker.patientendpoint.model.Patient.class);
    }

    @Override
    public InsertPatient setAlt(java.lang.String alt) {
      return (InsertPatient) super.setAlt(alt);
    }

    @Override
    public InsertPatient setFields(java.lang.String fields) {
      return (InsertPatient) super.setFields(fields);
    }

    @Override
    public InsertPatient setKey(java.lang.String key) {
      return (InsertPatient) super.setKey(key);
    }

    @Override
    public InsertPatient setOauthToken(java.lang.String oauthToken) {
      return (InsertPatient) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPatient setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPatient) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPatient setQuotaUser(java.lang.String quotaUser) {
      return (InsertPatient) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPatient setUserIp(java.lang.String userIp) {
      return (InsertPatient) super.setUserIp(userIp);
    }

    @Override
    public InsertPatient set(String parameterName, Object value) {
      return (InsertPatient) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPatient".
   *
   * This request holds the parameters needed by the the patientendpoint server.  After setting any
   * optional parameters, call the {@link ListPatient#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPatient listPatient() throws java.io.IOException {
    ListPatient result = new ListPatient();
    initialize(result);
    return result;
  }

  public class ListPatient extends PatientendpointRequest<com.prescriptiontracker.patientendpoint.model.CollectionResponsePatient> {

    private static final String REST_PATH = "patient";

    /**
     * Create a request for the method "listPatient".
     *
     * This request holds the parameters needed by the the patientendpoint server.  After setting any
     * optional parameters, call the {@link ListPatient#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPatient#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPatient() {
      super(Patientendpoint.this, "GET", REST_PATH, null, com.prescriptiontracker.patientendpoint.model.CollectionResponsePatient.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPatient setAlt(java.lang.String alt) {
      return (ListPatient) super.setAlt(alt);
    }

    @Override
    public ListPatient setFields(java.lang.String fields) {
      return (ListPatient) super.setFields(fields);
    }

    @Override
    public ListPatient setKey(java.lang.String key) {
      return (ListPatient) super.setKey(key);
    }

    @Override
    public ListPatient setOauthToken(java.lang.String oauthToken) {
      return (ListPatient) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPatient setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPatient) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPatient setQuotaUser(java.lang.String quotaUser) {
      return (ListPatient) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPatient setUserIp(java.lang.String userIp) {
      return (ListPatient) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPatient setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPatient setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPatient set(String parameterName, Object value) {
      return (ListPatient) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePatient".
   *
   * This request holds the parameters needed by the the patientendpoint server.  After setting any
   * optional parameters, call the {@link RemovePatient#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePatient removePatient(java.lang.String id) throws java.io.IOException {
    RemovePatient result = new RemovePatient(id);
    initialize(result);
    return result;
  }

  public class RemovePatient extends PatientendpointRequest<com.prescriptiontracker.patientendpoint.model.Patient> {

    private static final String REST_PATH = "patient/{id}";

    /**
     * Create a request for the method "removePatient".
     *
     * This request holds the parameters needed by the the patientendpoint server.  After setting any
     * optional parameters, call the {@link RemovePatient#execute()} method to invoke the remote
     * operation. <p> {@link RemovePatient#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePatient(java.lang.String id) {
      super(Patientendpoint.this, "DELETE", REST_PATH, null, com.prescriptiontracker.patientendpoint.model.Patient.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePatient setAlt(java.lang.String alt) {
      return (RemovePatient) super.setAlt(alt);
    }

    @Override
    public RemovePatient setFields(java.lang.String fields) {
      return (RemovePatient) super.setFields(fields);
    }

    @Override
    public RemovePatient setKey(java.lang.String key) {
      return (RemovePatient) super.setKey(key);
    }

    @Override
    public RemovePatient setOauthToken(java.lang.String oauthToken) {
      return (RemovePatient) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePatient setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePatient) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePatient setQuotaUser(java.lang.String quotaUser) {
      return (RemovePatient) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePatient setUserIp(java.lang.String userIp) {
      return (RemovePatient) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovePatient setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePatient set(String parameterName, Object value) {
      return (RemovePatient) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePatient".
   *
   * This request holds the parameters needed by the the patientendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePatient#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.prescriptiontracker.patientendpoint.model.Patient}
   * @return the request
   */
  public UpdatePatient updatePatient(com.prescriptiontracker.patientendpoint.model.Patient content) throws java.io.IOException {
    UpdatePatient result = new UpdatePatient(content);
    initialize(result);
    return result;
  }

  public class UpdatePatient extends PatientendpointRequest<com.prescriptiontracker.patientendpoint.model.Patient> {

    private static final String REST_PATH = "patient";

    /**
     * Create a request for the method "updatePatient".
     *
     * This request holds the parameters needed by the the patientendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePatient#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePatient#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.prescriptiontracker.patientendpoint.model.Patient}
     * @since 1.13
     */
    protected UpdatePatient(com.prescriptiontracker.patientendpoint.model.Patient content) {
      super(Patientendpoint.this, "PUT", REST_PATH, content, com.prescriptiontracker.patientendpoint.model.Patient.class);
    }

    @Override
    public UpdatePatient setAlt(java.lang.String alt) {
      return (UpdatePatient) super.setAlt(alt);
    }

    @Override
    public UpdatePatient setFields(java.lang.String fields) {
      return (UpdatePatient) super.setFields(fields);
    }

    @Override
    public UpdatePatient setKey(java.lang.String key) {
      return (UpdatePatient) super.setKey(key);
    }

    @Override
    public UpdatePatient setOauthToken(java.lang.String oauthToken) {
      return (UpdatePatient) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePatient setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePatient) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePatient setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePatient) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePatient setUserIp(java.lang.String userIp) {
      return (UpdatePatient) super.setUserIp(userIp);
    }

    @Override
    public UpdatePatient set(String parameterName, Object value) {
      return (UpdatePatient) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Patientendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Patientendpoint}. */
    @Override
    public Patientendpoint build() {
      return new Patientendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PatientendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPatientendpointRequestInitializer(
        PatientendpointRequestInitializer patientendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(patientendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
