/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-05 16:09:48 UTC)
 * on 2013-06-15 at 20:01:04 UTC 
 * Modify at your own risk.
 */

package com.prescriptiontracker.patientendpoint.model;

/**
 * Model definition for Patient.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Patient extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime patientDob;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String patientId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer patientMob;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String patientName;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getPatientDob() {
    return patientDob;
  }

  /**
   * @param patientDob patientDob or {@code null} for none
   */
  public Patient setPatientDob(com.google.api.client.util.DateTime patientDob) {
    this.patientDob = patientDob;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPatientId() {
    return patientId;
  }

  /**
   * @param patientId patientId or {@code null} for none
   */
  public Patient setPatientId(java.lang.String patientId) {
    this.patientId = patientId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPatientMob() {
    return patientMob;
  }

  /**
   * @param patientMob patientMob or {@code null} for none
   */
  public Patient setPatientMob(java.lang.Integer patientMob) {
    this.patientMob = patientMob;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPatientName() {
    return patientName;
  }

  /**
   * @param patientName patientName or {@code null} for none
   */
  public Patient setPatientName(java.lang.String patientName) {
    this.patientName = patientName;
    return this;
  }

  @Override
  public Patient set(String fieldName, Object value) {
    return (Patient) super.set(fieldName, value);
  }

  @Override
  public Patient clone() {
    return (Patient) super.clone();
  }

}
