/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-05 16:09:48 UTC)
 * on 2013-06-15 at 20:00:38 UTC 
 * Modify at your own risk.
 */

package com.prescriptiontracker.prescriptionendpoint.model;

/**
 * Model definition for UUID.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UUID extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long leastSignificantBits;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long mostSignificantBits;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLeastSignificantBits() {
    return leastSignificantBits;
  }

  /**
   * @param leastSignificantBits leastSignificantBits or {@code null} for none
   */
  public UUID setLeastSignificantBits(java.lang.Long leastSignificantBits) {
    this.leastSignificantBits = leastSignificantBits;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMostSignificantBits() {
    return mostSignificantBits;
  }

  /**
   * @param mostSignificantBits mostSignificantBits or {@code null} for none
   */
  public UUID setMostSignificantBits(java.lang.Long mostSignificantBits) {
    this.mostSignificantBits = mostSignificantBits;
    return this;
  }

  @Override
  public UUID set(String fieldName, Object value) {
    return (UUID) super.set(fieldName, value);
  }

  @Override
  public UUID clone() {
    return (UUID) super.clone();
  }

}
